const quizTopics = [
  {
    id: 'numpy', icon: '⌘', color: 'violet',
    title: 'Các lệnh NumPy cơ bản cần biết',
    description: 'Mảng đa chiều, tính toán vector và thao tác dữ liệu số.',
    questions: [
      { q: 'Lệnh nào tạo một mảng NumPy từ danh sách Python `[1, 2, 3]`?', choices: ['np.array([1, 2, 3])', 'np.list([1, 2, 3])', 'np.matrix(1, 2, 3)', 'np.create([1, 2, 3])'], answer: 0, correct: '`np.array()` chuyển sequence như list thành `ndarray`.', wrong: ['Đúng là API khởi tạo mảng chuẩn.', '`np.list()` không phải API của NumPy.', '`np.matrix` là kiểu ma trận cũ và cú pháp này không hợp lệ.', '`np.create()` không tồn tại trong NumPy.'] },
      { q: 'Với `a = np.array([1, 2, 3])`, biểu thức `a * 2` trả về gì?', choices: ['[1, 2, 3, 1, 2, 3]', '[2, 4, 6]', 'Lỗi kiểu dữ liệu', '[3, 4, 5]'], answer: 1, correct: 'NumPy nhân theo từng phần tử (element-wise), nên mỗi giá trị được nhân 2.', wrong: ['Đây là hành vi lặp list của Python, không phải mảng NumPy.', 'Đúng: phép toán được vector hóa theo từng phần tử.', 'Số nguyên có thể nhân với ndarray.', 'Đây là phép cộng 2, không phải nhân 2.'] },
      { q: 'Thuộc tính nào cho biết kích thước của mỗi chiều trong ndarray?', choices: ['dtype', 'size', 'shape', 'ndim'], answer: 2, correct: '`shape` trả về tuple kích thước theo từng trục, ví dụ `(3, 4)`.', wrong: ['`dtype` mô tả kiểu dữ liệu phần tử.', '`size` là tổng số phần tử, không chia theo chiều.', 'Đúng: `shape` biểu diễn kích thước từng chiều.', '`ndim` chỉ cho biết số chiều.'] },
      { q: 'Cách nào lấy toàn bộ các hàng nhưng chỉ cột thứ hai của `a` 2 chiều?', choices: ['a[1, :]', 'a[:, 1]', 'a[:, 2]', 'a[1]'], answer: 1, correct: 'Chỉ số `:` chọn mọi hàng, còn `1` chọn cột thứ hai vì index bắt đầu từ 0.', wrong: ['Biểu thức này lấy hàng thứ hai.', 'Đúng: mọi hàng ở cột có index 1.', 'Index 2 là cột thứ ba.', 'Với mảng 2D, cách này lấy nguyên hàng thứ hai.'] },
      { q: '`np.mean(a, axis=0)` tính gì với mảng 2 chiều?', choices: ['Trung bình từng hàng', 'Trung bình từng cột', 'Tổng tất cả phần tử', 'Phần tử lớn nhất'], answer: 1, correct: 'Giảm theo trục 0 nghĩa là gộp các hàng, còn lại một giá trị trung bình cho mỗi cột.', wrong: ['Trung bình từng hàng dùng `axis=1`.', 'Đúng: trục 0 bị giảm nên kết quả theo cột.', 'Phải dùng `np.sum(a)`.', 'Phải dùng `np.max(a)`.'] },
      { q: 'Lệnh nào đổi `a` có 12 phần tử thành ma trận 3 hàng, 4 cột mà không đổi dữ liệu?', choices: ['a.resize(3, 4, keep=True)', 'a.reshape(3, 4)', 'np.transform(a, 3, 4)', 'a.shape(3, 4)'], answer: 1, correct: '`reshape(3, 4)` trả về một view hoặc mảng có cùng dữ liệu với hình dạng mới khi khả thi.', wrong: ['`resize` có thể thay đổi tại chỗ nhưng cú pháp này sai và không phải lựa chọn thông dụng.', 'Đúng: `reshape` thay đổi hình dạng logic của mảng.', '`transform` không phải API này.', '`shape` là thuộc tính, không phải hàm gọi như vậy.'] },
    ]
  },
  {
    id: 'pandas', icon: '▦', color: 'teal',
    title: 'Các lệnh Pandas cơ bản cần biết', description: 'Đọc, lọc, tổng hợp và làm sạch bảng dữ liệu.',
    questions: [
      { q: 'Lệnh nào thường dùng để đọc một tệp CSV vào DataFrame?', choices: ['pd.open_csv("data.csv")', 'pd.read_csv("data.csv")', 'pd.load("data.csv")', 'pd.DataFrame.csv("data.csv")'], answer: 1, correct: '`pd.read_csv()` là hàm chuẩn để nạp CSV thành DataFrame.', wrong: ['Không có API `open_csv` trong pandas.', 'Đúng: đây là hàm đọc CSV chuẩn.', '`load` không phải hàm đọc CSV của pandas.', '`DataFrame.csv` không tồn tại.'] },
      { q: 'Với DataFrame `df`, `df.head()` mặc định hiển thị gì?', choices: ['5 hàng đầu tiên', '5 cột đầu tiên', 'Các hàng bị thiếu dữ liệu', 'Thông tin kiểu dữ liệu'], answer: 0, correct: '`head()` giúp xem nhanh 5 hàng đầu của DataFrame.', wrong: ['Đúng: mặc định xem 5 hàng đầu.', 'Muốn chọn cột cần index theo tên/cắt cột.', 'Lọc thiếu dữ liệu dùng `isna()`.', 'Kiểu dữ liệu xem bằng `info()` hoặc `dtypes`.'] },
      { q: 'Biểu thức nào lọc các hàng có `age` lớn hơn 18?', choices: ['df.age > 18', 'df.filter(age > 18)', 'df[df["age"] > 18]', 'df.where("age", 18)'], answer: 2, correct: 'Boolean mask `df[condition]` giữ lại các hàng có điều kiện đúng.', wrong: ['Biểu thức này chỉ tạo Series Boolean, chưa lọc DataFrame.', '`filter` chủ yếu chọn nhãn cột/hàng, không nhận điều kiện này.', 'Đúng: Boolean indexing là cú pháp lọc phổ biến.', '`where` có ngữ nghĩa khác và cú pháp này không đúng.'] },
      { q: 'Dùng phương thức nào để đếm số giá trị thiếu của từng cột?', choices: ['df.nulls()', 'df.isna().sum()', 'df.missing().count()', 'df.dropna().sum()'], answer: 1, correct: '`isna()` tạo mask thiếu dữ liệu; `sum()` đếm `True` theo từng cột.', wrong: ['Không có phương thức `nulls()` mặc định.', 'Đúng: đây là cách đếm NaN/NA phổ biến.', 'Không có chuỗi phương thức này.', '`dropna()` xóa dữ liệu trước, không dùng để đếm thiếu.'] },
      { q: '`df.groupby("city")["sales"].mean()` tạo ra kết quả nào?', choices: ['Trung bình sales của toàn bộ bảng', 'Trung bình sales cho từng city', 'Danh sách city duy nhất', 'Sắp xếp sales theo city'], answer: 1, correct: '`groupby` chia dữ liệu theo city, sau đó `mean()` tổng hợp sales trên mỗi nhóm.', wrong: ['Không có nhóm thì mới là trung bình toàn bảng.', 'Đúng: trả về một giá trị trung bình sales cho mỗi thành phố.', 'Dùng `unique()` để lấy các city khác nhau.', 'Cần `sort_values()` để sắp xếp.'] },
      { q: 'Khi cần ghép thêm các cột từ `right` vào `left` theo khóa `user_id`, phương thức phù hợp là?', choices: ['left.append(right)', 'left.merge(right, on="user_id")', 'left.stack(right)', 'left.concat(right, axis="rows")'], answer: 1, correct: '`merge` thực hiện phép join bảng theo khóa chung, tương tự SQL join.', wrong: ['`append` ghép theo hàng và đã không còn là API khuyến nghị.', 'Đúng: `merge` ghép dữ liệu theo `user_id`.', '`stack` thay đổi cấu trúc index, không join hai bảng theo khóa.', '`concat` không dùng cú pháp này và không xử lý join khóa mặc định.'] },
    ]
  },
  {
    id: 'ml', icon: 'ƒx', color: 'orange', title: 'Các công thức Machine Learning cơ bản cần biết', description: 'Loss, tối ưu hóa và đánh giá mô hình học máy.',
    questions: [
      { q: 'Mục tiêu của gradient descent là gì?', choices: ['Tăng loss nhanh nhất', 'Cập nhật tham số theo hướng làm giảm loss', 'Chọn nhiều đặc trưng hơn', 'Chia dữ liệu thành tập train/test'], answer: 1, correct: 'Gradient chỉ hướng tăng nhanh nhất; trừ gradient sẽ đi về hướng giảm loss cục bộ.', wrong: ['Gradient descent tối thiểu hóa, không tối đa hóa loss.', 'Đúng: cập nhật ngược chiều gradient để giảm loss.', 'Feature selection là bước khác.', 'Train/test split là bước chuẩn bị dữ liệu.'] },
      { q: 'Công thức cập nhật tham số cơ bản của gradient descent là?', choices: ['θ ← θ + α∇J(θ)', 'θ ← θ − α∇J(θ)', 'θ ← α / ∇J(θ)', 'θ ← ∇J(θ) − α'], answer: 1, correct: 'Ta trừ learning rate nhân gradient: `θ ← θ − α∇J(θ)`.', wrong: ['Dấu cộng đi theo hướng tăng loss.', 'Đúng: đây là công thức gradient descent.', 'Công thức này không phải cập nhật gradient descent.', 'Thứ tự toán học và ý nghĩa tham số đều không đúng.'] },
      { q: 'MSE trong hồi quy đo lường gì?', choices: ['Tỷ lệ dự đoán đúng', 'Trung bình bình phương sai số dự đoán', 'Khoảng cách lớn nhất giữa hai điểm', 'Số lượng đặc trưng'], answer: 1, correct: 'Mean Squared Error là trung bình của bình phương chênh lệch giữa dự đoán và nhãn thật.', wrong: ['Đó gần với accuracy của phân loại.', 'Đúng: sai số được bình phương rồi lấy trung bình.', 'Đó là một đại lượng khác.', 'MSE không đo số đặc trưng.'] },
      { q: 'Regularization L2 thường giúp giảm hiện tượng nào?', choices: ['Underfitting bằng cách làm mô hình phức tạp hơn', 'Overfitting bằng cách phạt trọng số lớn', 'Thiếu dữ liệu nhãn', 'Lỗi chia tập dữ liệu'], answer: 1, correct: 'L2 thêm penalty trọng số lớn, khuyến khích mô hình đơn giản và giảm overfitting.', wrong: ['L2 thường giảm độ phức tạp hiệu dụng, có thể làm underfitting tăng nếu quá mạnh.', 'Đúng: đây là tác dụng chính của L2.', 'Regularization không tạo thêm nhãn.', 'Nó không thay thế quy trình chia dữ liệu.'] },
      { q: 'Precision cao nói lên điều gì?', choices: ['Trong các mẫu dự đoán dương, nhiều mẫu thực sự dương', 'Mô hình tìm được hầu hết mẫu dương thật', 'Mô hình luôn có accuracy cao', 'Không có false negative'], answer: 0, correct: 'Precision = TP / (TP + FP), nên quan tâm độ tin cậy của dự đoán dương.', wrong: ['Đúng: ít false positive sẽ làm precision cao.', 'Đây là ý nghĩa của recall.', 'Accuracy phụ thuộc cả lớp âm và mất cân bằng lớp.', 'Không có false negative là recall 100%, không suy ra precision.'] },
      { q: 'Vì sao cần đánh giá trên validation/test set chưa dùng để huấn luyện?', choices: ['Để mô hình học thuộc dữ liệu tốt hơn', 'Để ước lượng khả năng tổng quát hóa trên dữ liệu mới', 'Để tăng số epoch', 'Để loại bỏ toàn bộ outlier'], answer: 1, correct: 'Tập chưa thấy giúp đo mô hình có hoạt động tốt với dữ liệu mới hay chỉ học thuộc train set.', wrong: ['Học thuộc làm giảm generalization.', 'Đúng: đây là mục tiêu của validation/test.', 'Epoch do quy trình huấn luyện quyết định.', 'Outlier cần được xử lý riêng.'] },
    ]
  },
  {
    id: 'dl', icon: '◉', color: 'pink', title: 'Các công thức Deep Learning cần nắm', description: 'Neuron, activation, backpropagation và kiến trúc mạng.',
    questions: [
      { q: 'Đầu ra trước activation của một neuron dense thường được tính bằng?', choices: ['z = w + x', 'z = wᵀx + b', 'z = x / b', 'z = σ(w) + b'], answer: 1, correct: 'Neuron lấy tổ hợp tuyến tính input và trọng số, rồi cộng bias: `z = wᵀx + b`.', wrong: ['Thiếu phép nhân/tổ hợp theo đặc trưng.', 'Đúng: đây là phép biến đổi affine trước activation.', 'Không phải công thức neuron dense.', 'Activation được áp dụng sau z, không thay thế input.'] },
      { q: 'Hàm ReLU được định nghĩa là?', choices: ['max(0, x)', '1 / (1 + eˣ)', 'x²', 'log(x)'], answer: 0, correct: 'ReLU giữ giá trị dương và đưa giá trị âm về 0: `max(0, x)`.', wrong: ['Đúng: đây là công thức ReLU.', 'Đây không phải sigmoid chuẩn; sigmoid là `1/(1+e^-x)`.', 'Đây là bình phương.', 'Đây là logarithm.'] },
      { q: 'Vai trò chính của backpropagation là gì?', choices: ['Tạo thêm dữ liệu huấn luyện', 'Tính gradient loss theo từng tham số bằng chain rule', 'Tăng số layer tự động', 'Chuẩn hóa toàn bộ input'], answer: 1, correct: 'Backprop truyền gradient từ loss ngược qua mạng để tính đạo hàm hiệu quả cho mọi trọng số.', wrong: ['Data augmentation là kỹ thuật riêng.', 'Đúng: backprop dùng chain rule để tính gradient.', 'Kiến trúc được người thiết kế/chọn qua tìm kiếm.', 'Chuẩn hóa input là bước preprocessing.'] },
      { q: 'Softmax thường được dùng ở đầu ra của bài toán nào?', choices: ['Hồi quy một giá trị liên tục', 'Phân loại nhiều lớp loại trừ nhau', 'Giảm chiều dữ liệu', 'Phát hiện giá trị thiếu'], answer: 1, correct: 'Softmax biến logits thành phân phối xác suất tổng bằng 1 cho các lớp loại trừ nhau.', wrong: ['Hồi quy thường dùng linear output.', 'Đúng: softmax phù hợp multiclass single-label.', 'Giảm chiều dùng các thuật toán khác.', 'Thiếu dữ liệu không xử lý bằng softmax.'] },
      { q: 'Dropout trong lúc huấn luyện giúp gì?', choices: ['Xóa vĩnh viễn các neuron yếu', 'Ngẫu nhiên tắt một phần activation để giảm overfitting', 'Tăng learning rate', 'Thay thế batch normalization'], answer: 1, correct: 'Dropout tạm thời đặt ngẫu nhiên một phần activation về 0 khi train để giảm phụ thuộc đồng thời.', wrong: ['Neuron không bị xóa vĩnh viễn.', 'Đúng: đây là cơ chế regularization của dropout.', 'Learning rate là hyperparameter riêng.', 'Batch normalization có mục đích/cơ chế khác.'] },
      { q: 'Vanishing gradient gây khó khăn chủ yếu cho điều gì?', choices: ['Các layer đầu nhận gradient quá nhỏ để học', 'Mô hình không thể đọc file ảnh', 'Loss luôn bằng 0', 'Dữ liệu bị trùng lặp'], answer: 0, correct: 'Khi gradient bị nhân qua nhiều đạo hàm nhỏ, các layer gần input gần như không được cập nhật.', wrong: ['Đúng: gradient quá nhỏ làm layer sớm học chậm hoặc không học.', 'Đó là vấn đề input pipeline.', 'Vanishing gradient không buộc loss bằng 0.', 'Không liên quan trực tiếp đến duplicate data.'] },
    ]
  },
  {
    id: 'math', icon: 'π', color: 'blue', title: 'Toán cần biết quanh Machine Learning & Deep Learning', description: 'Đại số tuyến tính, xác suất, đạo hàm và thống kê.',
    questions: [
      { q: 'Tích vô hướng của hai vector cùng chiều thường cho kết quả là?', choices: ['Một scalar', 'Một vector mới cùng chiều', 'Một ma trận vuông', 'Luôn bằng 0'], answer: 0, correct: 'Dot product cộng các tích phần tử tương ứng và cho ra một số (scalar).', wrong: ['Đúng: dot product của hai vector cho scalar.', 'Phép nhân từng phần tử mới cho vector.', 'Outer product mới có thể cho ma trận.', 'Chỉ bằng 0 nếu hai vector trực giao.'] },
      { q: 'Đạo hàm của hàm loss theo tham số biểu diễn điều gì?', choices: ['Số lượng dữ liệu', 'Tốc độ/hướng loss thay đổi khi tham số thay đổi', 'Xác suất của nhãn', 'Kích thước batch'], answer: 1, correct: 'Đạo hàm (gradient khi nhiều tham số) mô tả độ nhạy của loss theo từng tham số.', wrong: ['Không liên quan số mẫu.', 'Đúng: gradient cho biết hướng và mức thay đổi cục bộ.', 'Xác suất là đầu ra của mô hình/phân phối.', 'Batch size là thiết lập huấn luyện.'] },
      { q: 'Xác suất có điều kiện `P(A|B)` là gì?', choices: ['Xác suất A xảy ra khi đã biết B xảy ra', 'Xác suất A và B không xảy ra', 'Tổng xác suất của A và B', 'Trung bình của A, B'], answer: 0, correct: '`P(A|B)` cập nhật xác suất của A dưới điều kiện B đã xảy ra.', wrong: ['Đúng: dấu `|` đọc là “với điều kiện”.', 'Đây là sự kiện bù, không phải điều kiện.', 'Không phải phép cộng xác suất.', 'Không phải khái niệm trung bình.'] },
      { q: 'Variance cao của dữ liệu nói lên điều gì?', choices: ['Các giá trị thường xa trung bình hơn', 'Trung bình luôn bằng 0', 'Không có outlier', 'Số lượng mẫu rất lớn'], answer: 0, correct: 'Variance đo độ phân tán quanh mean; lớn hơn nghĩa là các giá trị phân tán hơn.', wrong: ['Đúng: độ phân tán quanh trung bình lớn.', 'Variance không quyết định mean.', 'Outlier có thể làm variance tăng.', 'Nó không trực tiếp cho biết số mẫu.'] },
      { q: 'Ma trận đơn vị I có tính chất nào?', choices: ['I·x = x', 'I·x = 0', 'I không thể nhân vector', 'Mọi phần tử đều bằng 1'], answer: 0, correct: 'Ma trận đơn vị là phần tử trung hòa của phép nhân ma trận: nhân với vector/ma trận tương thích không đổi giá trị.', wrong: ['Đúng: ma trận đơn vị giữ nguyên x.', 'Ma trận zero mới cho kết quả 0.', 'I có thể nhân với đối tượng phù hợp kích thước.', 'Chỉ đường chéo chính bằng 1, còn lại bằng 0.'] },
      { q: 'Tại sao cần chuẩn hóa/scale các feature trước nhiều mô hình?', choices: ['Để xóa nhãn dữ liệu', 'Để feature thang đo lớn không chi phối khoảng cách/gradient', 'Để mọi giá trị thành số nguyên', 'Để tăng số cột'], answer: 1, correct: 'Các thuật toán nhạy khoảng cách hoặc gradient hoạt động ổn định hơn khi feature có thang đo tương đương.', wrong: ['Nhãn cần cho supervised learning.', 'Đúng: scaling hạn chế sự chi phối do đơn vị đo.', 'Scaling không yêu cầu số nguyên.', 'Nó không tạo feature mới.'] },
    ]
  },
  {
    id: 'product', icon: '↗', color: 'green', title: 'Quy trình phần mềm, MVP và tăng trưởng người dùng', description: 'Tạo impact, kiểm chứng giá trị và vận hành ở quy mô lớn.',
    questions: [
      { q: 'Mục tiêu cốt lõi của MVP là gì?', choices: ['Xây mọi tính năng đối thủ có', 'Kiểm chứng giả thuyết giá trị bằng phiên bản nhỏ nhất khả dụng', 'Tối ưu hạ tầng cho hàng triệu users ngay', 'Loại bỏ hoàn toàn lỗi trước khi ra mắt'], answer: 1, correct: 'MVP tập trung vào vòng lặp học hỏi nhanh: đưa giá trị tối thiểu ra thị trường để kiểm chứng giả thuyết.', wrong: ['Điều này làm chậm học hỏi và tăng scope.', 'Đúng: MVP là sản phẩm nhỏ nhất để học/kiểm chứng giá trị.', 'Scale quá sớm trước product-market fit thường lãng phí.', 'Chất lượng quan trọng nhưng không thể bảo đảm không có lỗi.'] },
      { q: 'Một product metric phù hợp nhất để đo giá trị lặp lại của sản phẩm là?', choices: ['Số dòng code', 'Retention của nhóm người dùng mục tiêu', 'Số cuộc họp mỗi tuần', 'Số màu trong giao diện'], answer: 1, correct: 'Retention phản ánh người dùng có quay lại và tiếp tục nhận giá trị hay không.', wrong: ['Code volume không đo impact người dùng.', 'Đúng: retention đo giá trị được duy trì theo thời gian.', 'Cuộc họp là hoạt động nội bộ.', 'Màu giao diện không phải chỉ số giá trị cốt lõi.'] },
      { q: 'Trước khi xây tính năng lớn, bước nào giúp giảm rủi ro nhất?', choices: ['Viết toàn bộ code trước', 'Xác định giả thuyết, đối tượng và chỉ số thành công có thể đo', 'Tăng ngân sách quảng cáo ngay', 'Bỏ qua phản hồi của người dùng'], answer: 1, correct: 'Giả thuyết và metric rõ ràng giúp đội biết cần học gì, đo gì và quyết định tiếp tục hay điều chỉnh.', wrong: ['Xây trước dễ tạo chi phí sunk cost.', 'Đúng: đây là nền tảng cho thử nghiệm có ý nghĩa.', 'Quảng cáo không thay thế việc chứng minh giá trị.', 'Phản hồi người dùng là nguồn học quan trọng.'] },
      { q: 'A/B test đáng tin cậy cần so sánh gì?', choices: ['Hai phiên bản với nhóm người dùng được phân bổ ngẫu nhiên và metric xác định trước', 'Hai ảnh thiết kế do cùng một người chọn', 'Số commit của hai lập trình viên', 'Hai ngày bất kỳ có traffic khác nhau'], answer: 0, correct: 'Phân bổ ngẫu nhiên và metric định trước giúp giảm bias khi so sánh tác động của biến thể.', wrong: ['Đúng: đây là nguyên tắc cơ bản của A/B test.', 'Đánh giá chủ quan không đo tác động người dùng.', 'Commit không phải outcome sản phẩm.', 'Khác biệt traffic/thời điểm gây nhiễu.'] },
      { q: 'Khi lượng users tăng nhanh, nguyên tắc nào nên được ưu tiên?', choices: ['Chỉ mở rộng server thủ công khi hệ thống sập', 'Quan sát bằng metrics/logs, xác định bottleneck rồi scale có kiểm soát', 'Xóa dữ liệu cũ không cần kiểm tra', 'Tắt monitoring để giảm chi phí'], answer: 1, correct: 'Observability cho biết nghẽn ở đâu để đội chọn cách scale, cache, queue hay tối ưu đúng chỗ.', wrong: ['Phản ứng sau sự cố làm rủi ro cao.', 'Đúng: đo lường trước rồi scale theo bottleneck.', 'Xóa dữ liệu là rủi ro và không giải quyết nguyên nhân.', 'Monitoring rất cần khi quy mô tăng.'] },
      { q: 'Một roadmap tốt cho MVP nên được ưu tiên theo gì?', choices: ['Ý tưởng của người nói to nhất', 'Tác động người dùng, mức độ tin cậy và chi phí thực hiện', 'Thứ tự các tính năng được nghĩ ra', 'Số lượng ticket đóng được'], answer: 1, correct: 'Ưu tiên theo impact, confidence và effort giúp tối đa hóa học hỏi/giá trị với nguồn lực hữu hạn.', wrong: ['Đây là bias, không phải tiêu chí sản phẩm.', 'Đúng: đây là cách ưu tiên có cơ sở.', 'Thứ tự ý tưởng không phản ánh giá trị.', 'Đóng nhiều ticket không đồng nghĩa tác động lớn.'] },
    ]
  }
];

// Câu hỏi mở rộng từ "Cẩm nang NumPy & Pandas" và "Cẩm nang công thức ML & DL".
// Helper giữ dữ liệu gọn nhưng vẫn cung cấp phản hồi cho mọi phương án sai.
const sourceQuestion = (q, choices, answer, correct) => ({
  q, choices, answer, correct,
  wrong: choices.map((choice, index) => index === answer
    ? `Đây là đáp án đúng. ${correct}`
    : `\`${choice}\` chưa đúng. ${correct}`)
});
const addSourceQuestions = (topicId, questions) => {
  quizTopics.find((topic) => topic.id === topicId).questions.push(...questions);
};

addSourceQuestions('numpy', [
  sourceQuestion('Bài 1 — Với doanh thu 7 ngày, cách tạo ndarray đúng là?', ['np.array([120, 150, 90, 210, 180, 160, 200])', 'np.ndarray(120, 150, 90)', 'pd.array([120, 150])', 'np.zeros(120, 150)'], 0, '`np.array([...])` chuyển danh sách doanh thu thành ndarray.'),
  sourceQuestion('Bài 2 — Kho có 4 khu vực, mỗi khu 6 vị trí chưa có hàng. Mảng khởi tạo phù hợp là?', ['np.zeros((4, 6))', 'np.zeros(4, 6)', 'np.array(4, 6)', 'np.empty([4])'], 0, '`np.zeros((4, 6))` tạo ma trận 4 hàng, 6 cột toàn số 0.'),
  sourceQuestion('Bài 3 — Dãy giờ 0, 3, 6, ..., 21 được tạo bởi?', ['np.arange(0, 24, 3)', 'np.arange(0, 21, 3)', 'np.linspace(0, 24, 3)', 'np.range(0, 24, 3)'], 0, '`arange` không lấy cận phải, nên cận dừng phải là 24.'),
  sourceQuestion('Bài 4 — `scores` có 3 học sinh × 4 môn. Lấy điểm môn thứ ba của tất cả học sinh?', ['scores[:, 2]', 'scores[2, :]', 'scores[:, 3]', 'scores[2]'], 0, 'Cột thứ ba có index 2; `:` giữ tất cả học sinh.'),
  sourceQuestion('Bài 5 — Với `a = np.arange(1, 15)`, cách lấy phần tử cuối là?', ['a[-1]', 'a[14]', 'a[15]', 'a.last()'], 0, 'Index âm `-1` luôn truy cập phần tử cuối.'),
  sourceQuestion('Bài 6 — `np.arange(12).reshape(3, 4).T` có shape nào?', ['(4, 3)', '(3, 4)', '(12,)', '(2, 6)'], 0, 'Transpose hoán đổi hàng và cột: 3 × 4 thành 4 × 3.'),
  sourceQuestion('Bài 7 — Giá `[100, 250, 80, 400]` giảm 10% rồi cộng phí 5. Biểu thức vector hóa đúng?', ['np.round(prices * 0.9 + 5, 2)', 'prices * (0.9 + 5)', 'for p in prices: p * 0.9', 'np.sum(prices) * 0.9 + 5'], 0, 'Giảm từng giá bằng `* 0.9`, rồi cộng phí 5 cho từng phần tử.'),
  sourceQuestion('Bài 8 — Toán tử nào nhân ma trận theo quy tắc hàng–cột?', ['A @ B', 'A * B', 'A + B', 'A / B'], 0, '`@` là matrix multiplication; `*` chỉ nhân từng ô tương ứng.'),
  sourceQuestion('Bài 9 — Ma trận 2 chi nhánh × 5 ngày; tổng theo từng ngày dùng?', ['np.sum(visits, axis=0)', 'np.sum(visits, axis=1)', 'np.mean(visits)', 'np.argmax(visits)'], 0, 'Giảm theo trục hàng (axis 0) để còn một tổng cho mỗi cột/ngày.'),
  sourceQuestion('Bài 10 — Lọc nhiệt độ từ 32 trở lên trong `temperature`?', ['temperature[temperature >= 32]', 'temperature.where(32)', 'temperature >= 32', 'np.filter(temperature, 32)'], 0, 'Boolean indexing giữ các phần tử có điều kiện `>= 32` đúng.'),
  sourceQuestion('Bài 11 — Tạo nhãn "Hợp lệ" nếu giá từ 50 đến 500, ngược lại "Loại"?', ['np.where((p >= 50) & (p <= 500), "Hợp lệ", "Loại")', 'np.where(p >= 50 or p <= 500)', 'p[(p >= 50) and (p <= 500)]', 'np.ifelse(p, 50, 500)'], 0, 'Với mảng NumPy phải dùng `&` và ngoặc cho hai điều kiện, sau đó dùng `np.where`.'),
  sourceQuestion('Bài 12 — Muốn nhận cả mã sản phẩm duy nhất và số lần xuất hiện?', ['np.unique(ids, return_counts=True)', 'np.count(ids)', 'np.unique(ids)', 'np.value_counts(ids)'], 0, '`return_counts=True` trả về cặp giá trị duy nhất và số lần xuất hiện.'),
  sourceQuestion('Bài 13 — Lấy index theo thứ tự tăng dần để xếp hạng thời gian giao hàng?', ['np.argsort(delivery_time)', 'np.sort(delivery_time)', 'np.rank(delivery_time)', 'np.argmax(delivery_time)'], 0, '`argsort` trả về index sắp xếp; `sort` chỉ trả về các giá trị đã sắp.'),
  sourceQuestion('Bài 14 — Ghép hai batch 2D theo chiều hàng?', ['np.vstack([batch_1, batch_2])', 'np.hstack([batch_1, batch_2])', 'np.split(batch_1, batch_2)', 'batch_1 @ batch_2'], 0, '`vstack` chồng mảng theo chiều dọc, tức tăng số hàng.'),
  sourceQuestion('Bài 15 — Chia đều `np.arange(8)` thành 4 phần?', ['np.split(np.arange(8), 4)', 'np.reshape(np.arange(8), 4)', 'np.vstack(np.arange(8), 4)', 'np.slice(np.arange(8), 4)'], 0, '`np.split` chia mảng thành số phần bằng nhau khi kích thước phù hợp.'),
  sourceQuestion('Bài 16 — Tạo 7 số nguyên ngẫu nhiên 1..19 có thể tái lập?', ['np.random.default_rng(42).integers(1, 20, size=7)', 'np.random.randint(1, 19, seed=42)', 'np.random.normal(1, 20, 7)', 'np.arange(1, 20, 7)'], 0, 'Generator với seed 42 tạo kết quả tái lập; cận trên 20 không được lấy.'),
  sourceQuestion('Bài 17 — Sinh 5 giá trị nhiễu chuẩn có mean 0, std 1?', ['rng.normal(0, 1, size=5)', 'rng.integers(0, 1, size=5)', 'rng.uniform(0, 1, size=5)', 'np.zeros(5)'], 0, '`normal(0, 1, size=5)` lấy mẫu từ phân phối chuẩn chuẩn hóa.'),
  sourceQuestion('Bài 18 — Chọn ngẫu nhiên 3 mẫu khác nhau từ dữ liệu mà không lặp?', ['rng.choice(data, size=3, replace=False)', 'rng.choice(data, size=3, replace=True)', 'np.repeat(data, 3)', 'data[:3]'], 0, '`replace=False` bảo đảm không chọn lại cùng một phần tử.'),
  sourceQuestion('Bài 19 — Giải hệ tuyến tính `A x = b` ổn định bằng NumPy?', ['np.linalg.solve(A, b)', 'A / b', 'np.linalg.inverse(A, b)', 'np.solve(A, b)'], 0, '`np.linalg.solve(A, b)` giải trực tiếp hệ phương trình `A x = b`.'),
  sourceQuestion('Bài 20 — Chuẩn hóa vector `v` về độ dài 1 thường dùng?', ['v / np.linalg.norm(v)', 'v / np.mean(v)', 'np.sum(v)', 'v.reshape(1, -1)'], 0, 'Chia vector cho Euclidean norm của chính nó sẽ tạo vector có norm bằng 1.'),
]);

addSourceQuestions('pandas', [
  sourceQuestion('Bài 21 — Tạo DataFrame đánh giá khách hàng từ dictionary?', ['pd.DataFrame(data)', 'pd.array(data)', 'np.DataFrame(data)', 'pd.read_csv(data)'], 0, '`pd.DataFrame` tạo bảng từ dictionary các cột.'),
  sourceQuestion('Bài 22 — Tạo thêm cột doanh thu từ quantity và unit_price nên ưu tiên?', ['df["revenue"] = df["quantity"] * df["unit_price"]', 'df.revenue = sum(quantity, unit_price)', 'df.apply("revenue")', 'df.merge(quantity, unit_price)'], 0, 'Phép toán giữa hai Series được vector hóa theo từng hàng.'),
  sourceQuestion('Bài 23 — Đọc file bán hàng CSV vào DataFrame?', ['pd.read_csv("sales.csv")', 'pd.open_csv("sales.csv")', 'pd.DataFrame("sales.csv")', 'pd.load_csv("sales.csv")'], 0, '`pd.read_csv` là API đọc CSV chuẩn của pandas.'),
  sourceQuestion('Bài 24 — Xem nhanh số hàng/số cột của DataFrame?', ['df.shape', 'df.size()', 'df.columns()', 'df.info.shape'], 0, '`shape` là tuple `(số_hàng, số_cột)`.'),
  sourceQuestion('Bài 25 — Chọn hai cột name và score?', ['df[["name", "score"]]', 'df["name", "score"]', 'df.select("name", "score")', 'df.loc("name", "score")'], 0, 'Danh sách tên cột cần thêm một cặp ngoặc vuông bên ngoài.'),
  sourceQuestion('Bài 26 — Lọc học sinh vừa age >= 20 vừa score >= 8?', ['df[(df.age >= 20) & (df.score >= 8)]', 'df[df.age >= 20 and df.score >= 8]', 'df.filter(age >= 20, score >= 8)', 'df[(age >= 20) | (score >= 8)]'], 0, 'Kết hợp điều kiện Series bằng `&`, mỗi điều kiện cần được đặt trong ngoặc.'),
  sourceQuestion('Bài 27 — Xếp hạng nhân viên theo score giảm dần?', ['df.sort_values("score", ascending=False)', 'df.sort("score", descending=True)', 'df.rank("score")', 'df.sort_values("score", ascending=True)'], 0, '`ascending=False` đưa giá trị điểm cao lên đầu.'),
  sourceQuestion('Bài 28 — Điền tuổi thiếu bằng median?', ['df["age"].fillna(df["age"].median())', 'df["age"].dropna()', 'df["age"].mean().fillna()', 'df.fill("age", 0)'], 0, 'Median là giá trị thay thế ít nhạy với outlier; kết quả cần gán lại cột.'),
  sourceQuestion('Bài 29 — Xóa đơn hàng thiếu score nhưng giữ các hàng khác?', ['df.dropna(subset=["score"])', 'df.dropna()', 'df["score"].fillna(0)', 'df.remove("score")'], 0, '`subset` giới hạn việc loại hàng theo cột score.'),
  sourceQuestion('Bài 30 — Giữ bản ghi email cuối cùng khi xóa trùng?', ['df.drop_duplicates(subset=["email"], keep="last")', 'df.drop_duplicates("email", keep="first")', 'df.unique("email")', 'df.dropna(subset=["email"])'], 0, '`keep="last"` giữ dòng xuất hiện cuối trong mỗi nhóm email trùng.'),
  sourceQuestion('Bài 31 — Đổi tên cột score thành final_score?', ['df.rename(columns={"score": "final_score"})', 'df.rename("score", "final_score")', 'df.columns["score"] = "final_score"', 'df.replace("score", "final_score")'], 0, 'Đổi nhãn cột dùng mapping trong tham số `columns`.'),
  sourceQuestion('Bài 32 — Ép cột date sang datetime, giá trị lỗi thành NaT?', ['pd.to_datetime(df["date"], errors="coerce")', 'df["date"].astype("datetime")', 'pd.date(df["date"])', 'df.to_numeric("date")'], 0, '`errors="coerce"` chuyển giá trị không hợp lệ thành `NaT` để xử lý tiếp.'),
  sourceQuestion('Bài 33 — Đếm số mã student_id phân biệt?', ['df["student_id"].nunique()', 'df["student_id"].count()', 'df["student_id"].unique().sum()', 'df.nrows()'], 0, '`nunique()` đếm số giá trị khác nhau, không phải số dòng.'),
  sourceQuestion('Bài 34 — Tính doanh thu trung bình theo chi nhánh?', ['df.groupby("branch")["revenue"].mean()', 'df.mean("branch", "revenue")', 'df["branch"].mean()', 'df.groupby("revenue").branch()'], 0, 'Nhóm theo branch rồi tổng hợp Series revenue bằng `mean()`.'),
  sourceQuestion('Bài 35 — Tỷ lệ "Đạt" trong Series result được tính gọn bằng?', ['(df["result"] == "Đạt").mean()', 'df["result"].sum()', 'df["result"].count("Đạt") / 100', 'df.mean("Đạt")'], 0, 'Boolean `True/False` được pandas xem như 1/0, nên mean là tỷ lệ True.'),
  sourceQuestion('Bài 36 — Ghép orders với customers theo customer_id, giữ mọi đơn hàng?', ['orders.merge(customers, on="customer_id", how="left")', 'orders.concat(customers, on="customer_id")', 'orders.append(customers)', 'orders.stack(customers)'], 0, 'Left join giữ toàn bộ orders và lấy thông tin khách tương ứng nếu có.'),
  sourceQuestion('Bài 37 — Gộp dữ liệu Jan, Feb, Mar theo hàng và tạo index mới?', ['pd.concat([jan, feb, mar], ignore_index=True)', 'pd.merge([jan, feb, mar])', 'jan + feb + mar', 'pd.stack(jan, feb, mar)'], 0, '`concat` ghép các DataFrame; `ignore_index=True` tạo index liên tục.'),
  sourceQuestion('Bài 38 — Ánh xạ mã giới tính M/F thành Nam/Nữ?', ['df["gender"].map({"M": "Nam", "F": "Nữ"})', 'df["gender"].merge({"M": "Nam"})', 'df.map("gender")', 'df["gender"].astype("Nam")'], 0, '`Series.map(dictionary)` thay từng giá trị theo dictionary.'),
  sourceQuestion('Bài 39 — Gán nhãn chi tiêu theo điều kiện nhiều mức thường dùng?', ['np.select(conditions, labels, default="Khác")', 'df.groupby("spend").label()', 'pd.merge(conditions, labels)', 'df.dropna(conditions)'], 0, '`np.select` phù hợp khi có nhiều điều kiện và nhãn tương ứng.'),
  sourceQuestion('Bài 40 — Muốn mô tả một dòng theo vị trí thứ 3?', ['df.iloc[2]', 'df.loc[2]', 'df.row(3)', 'df[3]'], 0, '`iloc` lấy theo vị trí 0-based, nên vị trí thứ ba là 2.'),
  sourceQuestion('Bài 41 — Làm sạch tên: bỏ khoảng trắng thừa và viết hoa đầu từ?', ['df["name"].str.strip().str.title()', 'df["name"].clean().title()', 'df["name"].trim().upper()', 'pd.strip(df["name"])'], 0, 'String accessor `.str` cho phép ghép `strip()` và `title()` trên cả Series.'),
  sourceQuestion('Bài 42 — Tách email thành username và domain thành hai cột?', ['df["email"].str.split("@", n=1, expand=True)', 'df["email"].split("@")', 'pd.split(df["email"], "@")', 'df.explode("email")'], 0, '`expand=True` biến kết quả tách thành DataFrame các cột.'),
  sourceQuestion('Bài 43 — Tính số ngày giao hàng từ delivered_at và order_date?', ['(df["delivered_at"] - df["order_date"]).dt.days', 'df["delivered_at"] / df["order_date"]', 'df.date_diff()', 'df["order_date"].days'], 0, 'Hiệu hai datetime là timedelta; `.dt.days` lấy số ngày.'),
  sourceQuestion('Bài 44 — Trích tháng từ cột order_date đã là datetime?', ['df["order_date"].dt.month', 'df["order_date"].month()', 'pd.month(df["order_date"])', 'df["order_date"]["month"]'], 0, 'Datetime accessor `.dt.month` lấy tháng của từng dòng.'),
  sourceQuestion('Bài 45 — Đưa bảng điểm wide về long với name giữ nguyên?', ['pd.melt(scores, id_vars=["name"], var_name="subject", value_name="score")', 'pd.pivot(scores, "name")', 'scores.reshape(-1, 1)', 'scores.stack("name")'], 0, '`melt` chuyển các cột môn thành cặp subject/score dạng long.'),
  sourceQuestion('Bài 46 — Lấy top 5 sản phẩm theo revenue?', ['df.groupby("product")["revenue"].sum().nlargest(5)', 'df["product"].head(5)', 'df.sort_values("product").head(5)', 'df.count("product", 5)'], 0, 'Cần tổng revenue từng product trước, rồi dùng `nlargest(5)`.'),
  sourceQuestion('Bài 47 — Sau `merge`, kiểm tra hàng có tăng bất thường trước hết bằng?', ['So sánh số dòng và kiểm tra khóa join/validate', 'Luôn gọi drop_duplicates', 'Xóa tất cả cột NaN', 'Chỉ xem df.head()'], 0, 'Merge sai cardinality có thể nhân bản dòng; cần kiểm tra row count và ràng buộc khóa.'),
  sourceQuestion('Bài 48 — Khác biệt chính giữa `loc` và `iloc`?', ['loc theo nhãn, iloc theo vị trí số nguyên', 'loc theo vị trí, iloc theo nhãn', 'Cả hai chỉ chọn cột', 'Cả hai chỉ dùng cho Series'], 0, '`loc` dùng label/index name, còn `iloc` dùng vị trí 0-based.'),
]);

const formulaQuiz = (q, choices, answer, correct) => ({
  q, choices, answer, correct,
  wrong: choices.map((choice, index) => index === answer ? `Đúng. ${correct}` : `\`${choice}\` không phù hợp. ${correct}`)
});

quizTopics.push({
  id: 'formula-lab', icon: '∑', color: 'violet', kind: 'formula',
  title: 'Công thức ML/DL nền tảng',
  description: 'Flashcard, công thức LaTeX, ví dụ trực quan và quiz áp dụng.',
  cards: [
    { title: 'Trung bình, phương sai và độ lệch chuẩn', formula: '\\[\\mu = \\frac{1}{n}\\sum_{i=1}^{n}x_i,\\quad \\sigma^2 = \\frac{1}{n}\\sum_{i=1}^{n}(x_i-\\mu)^2,\\quad \\sigma = \\sqrt{\\sigma^2}\\]', explanation: 'Mean mô tả tâm dữ liệu; variance và standard deviation đo độ phân tán quanh mean.', example: 'Với \\(2,4,6\\): \\(\\mu=4\\), \\(\\sigma^2=8/3\\), \\(\\sigma\\approx1.63\\).' },
    { title: 'Standardization và Min–Max', formula: '\\[z=\\frac{x-\\mu}{\\sigma},\\qquad x_{scaled}=\\frac{x-x_{min}}{x_{max}-x_{min}}\\]', explanation: 'Standardization đưa dữ liệu về số độ lệch chuẩn; Min–Max thường đưa dữ liệu về khoảng 0 đến 1.', example: 'Nếu \\(x=70,\\mu=50,\\sigma=10\\) thì \\(z=2\\). Với min 0, max 100: \\(x_{scaled}=0.7\\).' },
    { title: 'Tích vô hướng', formula: '\\[\\mathbf{w}^\\top\\mathbf{x}=\\sum_{i=1}^{d}w_ix_i\\]', explanation: 'Dot product kết hợp các feature thành một scalar; đó là lõi của mô hình tuyến tính và neuron.', example: 'Với \\(w=(0.4,0.6),x=(5,3)\\): \\(w^\\top x=0.4\\times5+0.6\\times3=3.8\\).' },
    { title: 'Khoảng cách Euclid', formula: '\\[d(\\mathbf{x},\\mathbf{y})=\\sqrt{\\sum_{i=1}^{d}(x_i-y_i)^2}\\]', explanation: 'Đo khoảng cách đường chim bay giữa hai điểm; thường dùng trong KNN và clustering.', example: 'Từ \\((1,1)\\) đến \\((4,5)\\): \\(d=\\sqrt{3^2+4^2}=5\\).' },
    { title: 'Linear Regression', formula: '\\[\\hat{y}=\\mathbf{w}^\\top\\mathbf{x}+b\\]', explanation: 'Dự đoán một giá trị liên tục bằng tổ hợp tuyến tính của feature và bias.', example: 'Với \\(\\hat y=2x+3\\), khi \\(x=4\\) thì \\(\\hat y=11\\).' },
    { title: 'MSE và MAE', formula: '\\[MSE=\\frac{1}{n}\\sum(y_i-\\hat y_i)^2,\\qquad MAE=\\frac{1}{n}\\sum|y_i-\\hat y_i|\\]', explanation: 'MSE phạt mạnh sai số lớn vì bình phương; MAE dễ diễn giải theo đúng đơn vị đầu ra.', example: 'Sai số \\((-1,2)\\): \\(MSE=(1+4)/2=2.5\\), \\(MAE=(1+2)/2=1.5\\).' },
    { title: 'Gradient Descent', formula: '\\[\\theta \\leftarrow \\theta-\\eta\\nabla J(\\theta)\\]', explanation: 'Cập nhật tham số ngược chiều gradient để giảm loss; \\(\\eta\\) là learning rate.', example: 'Nếu \\(w=1\\), gradient \\(-8\\), \\(\\eta=0.1\\): \\(w_{new}=1-0.1(-8)=1.8\\).' },
    { title: 'Sigmoid', formula: '\\[\\sigma(z)=\\frac{1}{1+e^{-z}}\\]', explanation: 'Biến một logit thành xác suất từ 0 đến 1, phổ biến trong binary classification.', example: 'Khi \\(z=0\\), \\(\\sigma(0)=0.5\\). Khi z tăng, xác suất tiến gần 1.' },
    { title: 'Binary Cross-Entropy', formula: '\\[BCE=-\\frac{1}{n}\\sum[y\\log(\\hat p)+(1-y)\\log(1-\\hat p)]\\]', explanation: 'Loss cho nhãn nhị phân; phạt mạnh khi mô hình tự tin dự đoán sai.', example: 'Với \\(y=1,\\hat p=0.9\\), loss là \\(-\\log(0.9)\\approx0.105\\).' },
    { title: 'Precision, Recall và F1', formula: '\\[P=\\frac{TP}{TP+FP},\\quad R=\\frac{TP}{TP+FN},\\quad F1=\\frac{2PR}{P+R}\\]', explanation: 'Precision đo độ tin cậy của cảnh báo dương; Recall đo khả năng tìm đủ ca dương.', example: 'TP=40, FP=10, FN=20: \\(P=0.8\\), \\(R=2/3\\), \\(F1\\approx0.727\\).' },
    { title: 'ReLU', formula: '\\[ReLU(x)=\\max(0,x)\\]', explanation: 'Activation đơn giản: giữ giá trị dương và đưa giá trị âm về 0.', example: '\\(ReLU(-3)=0\\), còn \\(ReLU(2)=2\\).' },
    { title: 'Max Pooling', formula: '\\[y_{i,j}=\\max_{(m,n)\\in window}x_{i+m,j+n}\\]', explanation: 'Lấy giá trị lớn nhất trong mỗi vùng ảnh, giảm kích thước không gian và giữ đặc trưng nổi bật.', example: 'Window \\([1,3;2,0]\\) qua max pooling cho output \\(3\\).' },
    { title: 'Cosine Similarity', formula: '\\[cos(\\theta)=\\frac{\\mathbf{a}\\cdot\\mathbf{b}}{\\|\\mathbf{a}\\|\\|\\mathbf{b}\\|}\\]', explanation: 'Đo mức cùng hướng của hai vector, ít bị ảnh hưởng bởi độ dài vector.', example: 'Hai vector cùng hướng có cosine gần \\(1\\); trực giao có cosine \\(0\\).' },
    { title: 'Naive Bayes', formula: '\\[P(C\\mid\\mathbf{x})\\propto P(C)\\prod_iP(x_i\\mid C)\\]', explanation: 'Dùng Bayes và giả định các feature độc lập có điều kiện theo lớp.', example: 'Trong lọc spam, các từ xuất hiện cung cấp likelihood để so sánh \\(P(spam\\mid words)\\) và \\(P(ham\\mid words)\\).' },
    { title: 'L1 và L2 Regularization', formula: '\\[L_{L1}=L+\\lambda\\sum|w_i|,\\qquad L_{L2}=L+\\lambda\\sum w_i^2\\]', explanation: 'L1 khuyến khích trọng số thưa; L2 phạt trọng số lớn để mô hình mượt và ít overfit hơn.', example: 'Khi \\(\\lambda\\) tăng, penalty tăng; cần cân bằng để không gây underfitting.' },
  ],
  questions: [
    formulaQuiz('Mean của \\(x=(2,4,6)\\) bằng?', ['\\(4\\)', '\\(3\\)', '\\(12\\)', '\\(2\\)'], 0, '\\(\\mu=(2+4+6)/3=4\\).'),
    formulaQuiz('Đại lượng nào cùng đơn vị với dữ liệu gốc?', ['Độ lệch chuẩn', 'Phương sai', 'Bình phương sai số', 'Covariance matrix'], 0, 'Độ lệch chuẩn là căn bậc hai variance nên trở lại đơn vị gốc.'),
    formulaQuiz('Với \\(x=70,\\mu=50,\\sigma=10\\), z-score là?', ['\\(2\\)', '\\(0.5\\)', '\\(20\\)', '\\(7\\)'], 0, '\\(z=(70-50)/10=2\\).'),
    formulaQuiz('Min–Max scaling chủ yếu đưa feature về?', ['Khoảng xác định như 0–1', 'Mean bằng 0 tuyệt đối', 'Chỉ số nguyên', 'Variance bằng 1'], 0, 'Min–Max dùng min/max để đưa giá trị về khoảng mục tiêu, thường 0–1.'),
    formulaQuiz('Với \\(w=(0.4,0.6),x=(5,3)\\), \\(w^\\top x\\) bằng?', ['\\(3.8\\)', '\\(4.8\\)', '\\(15\\)', '\\(1\\)'], 0, '\\(0.4\\times5+0.6\\times3=3.8\\).'),
    formulaQuiz('Tích vô hướng của hai vector cùng chiều trả về?', ['Một scalar', 'Luôn một ma trận', 'Một vector cùng chiều', 'Một Boolean'], 0, 'Dot product cộng các tích thành phần tử tương ứng nên cho một scalar.'),
    formulaQuiz('Khoảng cách Euclid từ \\((1,1)\\) đến \\((4,5)\\) là?', ['\\(5\\)', '\\(7\\)', '\\(4\\)', '\\(\\sqrt{41}\\)'], 0, '\\(\\sqrt{(4-1)^2+(5-1)^2}=\\sqrt{25}=5\\).'),
    formulaQuiz('KNN thường dựa trực tiếp vào đại lượng nào để tìm láng giềng?', ['Khoảng cách giữa các feature đã scale', 'Bias của mô hình', 'Số epoch', 'Cross-entropy'], 0, 'KNN so sánh khoảng cách; cần scale feature để thang đo không chi phối.'),
    formulaQuiz('Với \\(\\hat y=2x+3\\), dự đoán tại \\(x=4\\) là?', ['\\(11\\)', '\\(8\\)', '\\(14\\)', '\\(5\\)'], 0, '\\(2\\times4+3=11\\).'),
    formulaQuiz('Trong \\(\\hat y=w^\\top x+b\\), \\(b\\) là gì?', ['Bias/intercept', 'Batch size', 'Binary label', 'Learning rate'], 0, 'b là intercept/bias, dịch dự đoán độc lập với feature.'),
    formulaQuiz('Sai số \\((-1,2)\\) có MSE bằng?', ['\\(2.5\\)', '\\(1.5\\)', '\\(5\\)', '\\(3\\)'], 0, '\\(MSE=((-1)^2+2^2)/2=(1+4)/2=2.5\\).'),
    formulaQuiz('Khi outlier rất lớn cần bị phạt mạnh hơn, nên ưu tiên?', ['MSE', 'MAE', 'Accuracy', 'Recall'], 0, 'MSE bình phương sai số nên outlier đóng góp lớn hơn MAE.'),
    formulaQuiz('Gradient descent cập nhật tham số theo hướng nào?', ['Ngược chiều gradient', 'Cùng chiều gradient', 'Ngẫu nhiên hoàn toàn', 'Theo nhãn lớn nhất'], 0, '\\(\\theta\\leftarrow\\theta-\\eta\\nabla J\\) đi ngược hướng loss tăng nhanh nhất.'),
    formulaQuiz('Nếu \\(w=1\\), gradient \\(-8\\), \\(\\eta=0.1\\), w mới là?', ['\\(1.8\\)', '\\(0.2\\)', '\\(-7\\)', '\\(9\\)'], 0, '\\(1-0.1(-8)=1.8\\).'),
    formulaQuiz('Sigmoid(0) bằng?', ['\\(0.5\\)', '\\(0\\)', '\\(1\\)', '\\(e\\)'], 0, '\\(1/(1+e^0)=1/2=0.5\\).'),
    formulaQuiz('Đầu ra Sigmoid luôn nằm trong khoảng?', ['\\((0,1)\\)', '\\((-\\infty,\\infty)\\)', '\\([0,\\infty)\\)', '\\([-1,1]\\)'], 0, 'Sigmoid biến logit thành xác suất mở trong khoảng 0 đến 1.'),
    formulaQuiz('Với \\(y=1,\\hat p=0.9\\), BCE một mẫu là?', ['\\(-\\log(0.9)\\)', '\\(-\\log(0.1)\\)', '\\(0.9\\)', '\\(1-0.9\\)'], 0, 'Khi y=1, chỉ hạng \\(-\\log(\\hat p)\\) còn lại.'),
    formulaQuiz('BCE tăng mạnh nhất khi nào?', ['Mô hình tự tin nhưng dự đoán sai', 'Mô hình dự đoán đúng xác suất gần 1', 'Nhãn bằng 0', 'Batch size lớn'], 0, 'Log loss phạt mạnh xác suất rất nhỏ đặt cho lớp đúng.'),
    formulaQuiz('Precision được tính bằng?', ['\\(TP/(TP+FP)\\)', '\\(TP/(TP+FN)\\)', '\\((TP+TN)/N\\)', '\\(2PR\\)'], 0, 'Precision là tỷ lệ dự đoán dương thực sự đúng.'),
    formulaQuiz('Khi bỏ sót ca bệnh nguy hiểm rất tốn kém, metric ưu tiên là?', ['Recall', 'Precision', 'MSE', 'R²'], 0, 'Recall giảm false negative, tức giảm bỏ sót ca dương tính.'),
    formulaQuiz('ReLU(-3) bằng?', ['\\(0\\)', '\\(-3\\)', '\\(3\\)', '\\(0.5\\)'], 0, '\\(ReLU(x)=max(0,x)\\), nên input âm thành 0.'),
    formulaQuiz('Ưu điểm thực dụng chính của ReLU so với sigmoid ở hidden layer?', ['Giảm nguy cơ vanishing gradient ở miền dương', 'Luôn cho xác suất', 'Không có đạo hàm', 'Chỉ nhận input âm'], 0, 'ReLU có gradient 1 ở miền dương, thường giúp mạng sâu học hiệu quả hơn sigmoid.'),
    formulaQuiz('Max pooling trên window \\([1,3;2,0]\\) cho output?', ['\\(3\\)', '\\(1.5\\)', '\\(6\\)', '\\(0\\)'], 0, 'Max pooling giữ giá trị lớn nhất trong window: 3.'),
    formulaQuiz('Tác dụng chính của max pooling trong CNN?', ['Giảm kích thước không gian và giữ activation nổi bật', 'Tăng số channel', 'Tạo nhãn mới', 'Chuẩn hóa về mean 0'], 0, 'Pooling downsample feature map nhưng giữ phản hồi mạnh nhất ở mỗi vùng.'),
    formulaQuiz('Cosine similarity của hai vector cùng hướng là gần?', ['\\(1\\)', '\\(0\\)', '\\(-1\\)', '\\(\\infty\\)'], 0, 'Vector cùng hướng có góc gần 0 nên cosine gần 1.'),
    formulaQuiz('Cosine similarity ít bị ảnh hưởng bởi?', ['Độ dài tuyệt đối của vector', 'Hướng vector', 'Tích vô hướng', 'Góc giữa vector'], 0, 'Mẫu số chuẩn hóa bằng norm nên cosine tập trung vào hướng.'),
    formulaQuiz('Giả định “naive” trong Naive Bayes là?', ['Feature độc lập có điều kiện theo lớp', 'Các lớp có prior bằng nhau', 'Không cần dữ liệu train', 'Feature luôn Gaussian'], 0, 'Naive Bayes giả định các feature độc lập khi đã biết class.'),
    formulaQuiz('Trong lọc spam, \\(P(spam)\\) biểu diễn?', ['Prior xác suất email là spam trước khi xem từ', 'Likelihood của từ cho ham', 'Loss của mô hình', 'Learning rate'], 0, 'Prior là xác suất lớp trước khi quan sát feature.'),
    formulaQuiz('Regularization nào khuyến khích nhiều trọng số đúng bằng 0?', ['L1', 'L2', 'Dropout', 'BatchNorm'], 0, 'L1 dùng tổng trị tuyệt đối, thường tạo nghiệm thưa/sparse.'),
    formulaQuiz('L2 regularization phạt đại lượng nào?', ['Tổng bình phương trọng số', 'Số feature bằng 0', 'Tổng nhãn', 'Sai số tuyệt đối duy nhất'], 0, 'L2 thêm \\(\\lambda\\sum w_i^2\\) để hạn chế trọng số quá lớn.'),
  ]
});

addSourceQuestions('math', [
  sourceQuestion('Bài 1 — w=[0.4, 0.6], x=[5, 3], b=1. z = wᵀx+b bằng?', ['4.8', '3.8', '5.0', '2.2'], 0, 'z = 0.4×5 + 0.6×3 + 1 = 2 + 1.8 + 1 = 4.8.'),
  sourceQuestion('Bài 2 — Khoảng cách Euclid giữa A(1,1) và B(4,5) là?', ['5', '7', '3', '√41'], 0, '√((4−1)² + (5−1)²) = √(9+16) = 5.'),
  sourceQuestion('Bài 3 — Dữ liệu [2,4,6,8], variance chia cho n bằng?', ['5', '4', '20', '√5'], 0, 'Mean = 5; tổng bình phương độ lệch = 9+1+1+9=20; variance = 20/4=5.'),
  sourceQuestion('Bài 4 — x=70, μ=50, σ=10 có z-score?', ['2', '20', '0.5', '7'], 0, 'z = (70−50)/10 = 2.'),
  sourceQuestion('Bài 5 — L(w)=(w−5)² tại w=1 có dL/dw?', ['-8', '-4', '8', '16'], 0, 'dL/dw = 2(w−5); tại w=1 là 2×(−4)=−8.'),
  sourceQuestion('Bài 6 — Từ w=1, gradient -8 và η=0.1, gradient descent cho w mới?', ['1.8', '0.2', '−7', '9'], 0, 'w mới = 1 − 0.1×(−8) = 1.8.'),
]);

addSourceQuestions('ml', [
  sourceQuestion('Bài 7 — ŷ=2x+3, x=4. Dự đoán là?', ['11', '8', '14', '5'], 0, 'Thay x=4: 2×4+3=11.'),
  sourceQuestion('Bài 8 — y=[3,5,7], ŷ=[2,6,10]. MAE bằng?', ['5/3 ≈ 1.67', '2', '4', '1'], 0, 'Sai số tuyệt đối là 1,1,3; MAE=(1+1+3)/3=5/3 ≈ 1.67.'),
  sourceQuestion('Bài 9 — Sigmoid(0) bằng?', ['0.5', '0', '1', '0.693'], 0, 'σ(0)=1/(1+e⁰)=1/2=0.5.'),
  sourceQuestion('Bài 10 — TP=40, FP=10, FN=20, TN=30. Precision bằng?', ['0.8', '0.7', '2/3', '0.5'], 0, 'Precision = TP/(TP+FP) = 40/50 = 0.8.'),
  sourceQuestion('Bài 11 — Precision=0.8, Recall=0.5. F1 gần bằng?', ['0.615', '0.4', '0.65', '1.3'], 0, 'F1=2PR/(P+R)=2×0.8×0.5/1.3≈0.615.'),
  sourceQuestion('Bài 12 — KNN K=5 có 3 láng giềng lớp A, 2 lớp B. Dự đoán?', ['Lớp A', 'Lớp B', 'Không dự đoán được', 'Cả A và B'], 0, 'KNN phân loại theo đa số phiếu; A nhận 3/5 phiếu.'),
  sourceQuestion('Bài 13 — Centroid của (1,2), (3,4), (5,6) là?', ['(3,4)', '(9,12)', '(2,3)', '(5,6)'], 0, 'Lấy trung bình từng tọa độ: ((1+3+5)/3, (2+4+6)/3) = (3,4).'),
  sourceQuestion('Bài 14 — Node nhị phân p1=p2=0.5 có Gini?', ['0.5', '1', '0', '0.25'], 0, 'Gini = 1 − (0.5²+0.5²) = 0.5.'),
  sourceQuestion('Bài 19 — Thực tế [100,50], dự đoán [90,70]. WAPE bằng?', ['20/150 ≈ 13.33%', '30/150 = 20%', '20/2 = 10%', '10/150 ≈ 6.67%'], 1, 'Tổng sai số tuyệt đối = 10+20=30, nên WAPE thực tế là 30/150=20%.'),
  sourceQuestion('Bài 21 — Vì sao accuracy dễ gây hiểu nhầm khi 99% mẫu là lớp âm?', ['Dự đoán toàn âm đã đạt 99% nhưng bỏ sót lớp dương', 'Accuracy luôn thấp hơn precision', 'Không thể tính accuracy', 'Chỉ dùng cho hồi quy'], 0, 'Dữ liệu mất cân bằng khiến accuracy cao không đảm bảo mô hình nhận diện được lớp hiếm.'),
  sourceQuestion('Bài 22 — Nếu bỏ sót bệnh nguy hiểm gây hậu quả lớn, ưu tiên metric nào?', ['Recall', 'Precision', 'Accuracy', 'MSE'], 0, 'Recall giảm false negative, tức giảm nguy cơ bỏ sót ca bệnh dương tính.'),
  sourceQuestion('Bài 23 — KNN gặp feature thu nhập lớn hơn tuổi hàng triệu lần sẽ?', ['Khoảng cách bị thu nhập chi phối; cần scale feature', 'KNN tự bỏ feature thu nhập', 'Không ảnh hưởng khoảng cách', 'Chỉ cần tăng K'], 0, 'KNN dựa khoảng cách nên phải chuẩn hóa để thang đo lớn không áp đảo.'),
  sourceQuestion('Bài 24 — Train tốt nhưng test kém thường là gì?', ['Overfitting; có thể regularize hoặc thêm dữ liệu', 'Underfitting; luôn tăng epoch', 'Data leakage; luôn tăng learning rate', 'Không có vấn đề'], 0, 'Chênh lệch train/test lớn là dấu hiệu overfitting; regularization, thêm dữ liệu hay đơn giản hóa mô hình có thể giúp.'),
]);

addSourceQuestions('dl', [
  sourceQuestion('Bài 15 — Softmax [0.1,0.7,0.2], nhãn đúng lớp 2. Cross-Entropy bằng?', ['−log(0.7) ≈ 0.357', '−log(0.2) ≈ 1.609', '0.7', '1−0.7=0.3'], 0, 'Với one-hot, chỉ xác suất lớp đúng đóng góp: −log(0.7)≈0.357.'),
  sourceQuestion('Bài 16 — ReLU nhận x=-3 và x=2 cho output?', ['0 và 2', '−3 và 2', '0 và 0', '−3 và 0'], 0, 'ReLU(x)=max(0,x), nên ReLU(−3)=0 và ReLU(2)=2.'),
  sourceQuestion('Bài 17 — Ảnh 32×32, kernel 5, padding 0, stride 1 có spatial output?', ['28×28', '32×32', '27×27', '36×36'], 0, 'Hout=floor((32+0−5)/1)+1=28; chiều rộng tương tự.'),
  sourceQuestion('Bài 18 — Conv Cin=3, Cout=16, kernel 3×3, có bias có bao nhiêu tham số?', ['448', '432', '144', '16'], 0, 'Mỗi filter có 3×3×3 trọng số + 1 bias = 28; 16 filter: 28×16=448.'),
  sourceQuestion('Bài 25 — Attention weights [0.5,0.3,0.2], values [6,2,1] cho tổng?', ['3.8', '9', '4.2', '3'], 0, 'Tổng có trọng số = 0.5×6 + 0.3×2 + 0.2×1 = 3.8.'),
]);

addSourceQuestions('product', [
  sourceQuestion('Bài 20 — Hệ thống xử lý 12,000 tin trong 2 phút có throughput?', ['100 tin/giây', '200 tin/giây', '6,000 tin/giây', '60 tin/giây'], 0, '2 phút = 120 giây; throughput = 12,000/120 = 100 tin/giây.'),
  sourceQuestion('Trong pipeline ML, bước nào giúp tránh data leakage?', ['Xác định thời điểm dự đoán trước khi chọn feature', 'Trộn test vào train để đủ dữ liệu', 'Chỉ tối ưu metric train', 'Bỏ validation set'], 0, 'Feature chỉ được dùng nếu có sẵn tại thời điểm cần dự đoán; điều này tránh rò rỉ thông tin tương lai.'),
  sourceQuestion('Khi triển khai thử nghiệm ML nhỏ, bộ theo dõi phù hợp nhất?', ['Latency, throughput và chất lượng dự đoán thực tế', 'Chỉ số dòng code', 'Số màu giao diện', 'Số lượng layer mô hình'], 0, 'Hệ thống cần được đánh giá cả hiệu năng vận hành lẫn chất lượng outcome thực tế.'),
  sourceQuestion('Baseline đơn giản nên được tạo trước khi dùng mô hình phức tạp vì?', ['Tạo mốc so sánh giá trị và phát hiện cải thiện thật', 'Luôn cho accuracy cao nhất', 'Không cần dữ liệu', 'Loại bỏ nhu cầu validation'], 0, 'Baseline cho biết mô hình phức tạp có thực sự mang lại giá trị vượt trội hay không.'),
]);

// Case thực tế: mỗi case yêu cầu chọn một quyết định xử lý dữ liệu phù hợp nhất.
const caseQuestion = (q, choices, answer, correct, wrong) => ({ q, choices, answer, correct, wrong });

addSourceQuestions('numpy', [
  caseQuestion('Case: Một cửa hàng có doanh thu 7 ngày trong list `sales`. Bạn cần tính doanh thu trung bình mà không viết vòng lặp. Chọn cách phù hợp nhất.', ['np.mean(np.array(sales))', 'sum(sales) / 7 bằng vòng lặp', 'pd.DataFrame(sales).groupby()', 'np.sort(sales)'], 0, '`np.mean` tính trung bình vector hóa trực tiếp trên ndarray.', ['Đúng: chuyển list sang ndarray rồi dùng mean là cách NumPy rõ ràng, vector hóa.', 'Vòng lặp không cần thiết và không tận dụng NumPy.', 'GroupBy là thao tác Pandas cho bảng dữ liệu, không cần cho một vector.', 'Sắp xếp không tính trung bình.']),
  caseQuestion('Case: Hệ thống cảm biến lưu 24 lần đo liên tiếp. Bạn muốn xem thành 6 giờ, mỗi giờ 4 lần đo. Đoạn code nào đúng?', ['readings.reshape(6, 4)', 'readings.reshape(4, 6, 1)', 'np.split(readings, 6)', 'readings.T'], 0, '`reshape(6, 4)` đổi cách nhìn 24 phần tử thành ma trận 6×4 mà không đổi dữ liệu.', ['Đúng: 6×4 vẫn có đúng 24 phần tử.', 'Shape này đòi 24 phần tử nhưng thêm chiều không cần cho yêu cầu biểu diễn 6 giờ × 4 lần.', 'split tạo 6 mảng rời, không phải ma trận 2D mong muốn.', 'Transpose chỉ có ý nghĩa sau khi mảng đã là 2D.']),
  caseQuestion('Case: Ma trận `stock` có hàng là kho, cột là mặt hàng. Cần tăng 10 đơn vị cho toàn bộ kho thứ hai. Chọn lệnh đúng.', ['stock[1, :] += 10', 'stock[:, 1] += 10', 'stock[2] += 10', 'stock += 10'], 0, 'Index 1 là kho thứ hai và `:` chọn toàn bộ cột/mặt hàng.', ['Đúng: cập nhật toàn bộ hàng thứ hai.', 'Biểu thức này cập nhật mặt hàng thứ hai ở mọi kho.', 'Index 2 là kho thứ ba.', 'Lệnh này tăng toàn bộ tồn kho, vượt phạm vi yêu cầu.']),
  caseQuestion('Case: Giá sản phẩm `prices` cần giảm 10% rồi cộng phí đóng gói 5 cho từng sản phẩm. Chọn biểu thức chính xác.', ['prices * 0.9 + 5', 'prices * (0.9 + 5)', 'np.sum(prices) * 0.9 + 5', 'prices + 0.9 * 5'], 0, 'NumPy áp dụng hai phép toán theo từng phần tử: giảm giá rồi cộng phí.', ['Đúng: phép toán vector hóa cho từng giá.', 'Cộng 0.9 và 5 trước sẽ nhân giá với 5.9, sai nghiệp vụ.', 'Tổng toàn bộ giá làm mất giá trị từng sản phẩm.', 'Biểu thức này chỉ cộng 4.5, không giảm giá 10%.']),
  caseQuestion('Case: Một dashboard cần chỉ giữ các lần đo nhiệt độ từ 32°C trở lên trong mảng `temp`. Cách lọc đúng?', ['temp[temp >= 32]', 'temp >= 32', 'np.where(temp >= 32)', 'temp[32]'], 0, 'Boolean mask giữ lại chính các giá trị thỏa ngưỡng.', ['Đúng: mask Boolean được dùng để lấy các phần tử nóng.', 'Biểu thức này chỉ trả về mask True/False, chưa trả dữ liệu nhiệt độ.', 'Không có giá trị thay thế nên `where` này trả index, không phải mảng nhiệt độ cần xem.', 'Đây là truy cập một index cố định, không phải điều kiện.']),
  caseQuestion('Case: Cần gắn nhãn "Nóng" cho nhiệt độ >=32, ngược lại "Bình thường" trên cả mảng. Chọn lệnh phù hợp.', ['np.where(temp >= 32, "Nóng", "Bình thường")', 'temp[temp >= 32] = "Nóng"', 'np.filter(temp, 32)', 'temp == "Nóng"'], 0, '`np.where` chọn một trong hai nhãn cho từng phần tử theo điều kiện.', ['Đúng: tạo mảng nhãn song song với nhiệt độ.', 'Lệnh này trộn chuỗi vào mảng số và chỉ xử lý nhánh nóng, mất nhãn còn lại.', 'NumPy không có API filter này.', 'Đây là phép so sánh, không tạo nhãn.']),
  caseQuestion('Case: Log đơn hàng chứa mã sản phẩm lặp lại. Bạn cần báo cáo mỗi mã và số lần xuất hiện. Chọn lệnh.', ['np.unique(product_ids, return_counts=True)', 'np.unique(product_ids)', 'np.count(product_ids)', 'np.sort(product_ids)'], 0, '`return_counts=True` trả về đồng thời mã duy nhất và tần suất.', ['Đúng: kết quả có cả values lẫn counts.', 'Thiếu số lần xuất hiện.', 'NumPy không có hàm `np.count` cho mục đích này.', 'Sắp xếp không tạo bảng tần suất.']),
  caseQuestion('Case: Đội vận hành muốn gọi lại 5 đơn hàng giao chậm nhất theo index của mảng `delivery_minutes`. Chọn bước đầu tiên đúng.', ['np.argsort(delivery_minutes)[-5:]', 'np.sort(delivery_minutes)[-5:]', 'np.argmax(delivery_minutes)', 'delivery_minutes[-5:]'], 0, '`argsort` trả index theo thứ tự; 5 index cuối là các giá trị lớn nhất.', ['Đúng: giữ được index để truy ngược đơn hàng.', 'sort chỉ trả giá trị phút, làm mất index đơn hàng.', 'argmax chỉ trả một đơn hàng chậm nhất.', 'Năm phần tử cuối theo thứ tự lưu không đồng nghĩa chậm nhất.']),
  caseQuestion('Case: Hai nhà máy gửi `batch_a` và `batch_b`, mỗi batch có cùng số cột đặc trưng. Cần gộp thêm bản ghi theo hàng.', ['np.vstack([batch_a, batch_b])', 'np.hstack([batch_a, batch_b])', 'batch_a @ batch_b', 'np.split(batch_a, batch_b)'], 0, '`vstack` chồng hai batch theo chiều dọc, tăng số bản ghi.', ['Đúng: giữ cấu trúc cột và cộng số hàng.', 'hstack ghép thêm cột, không phải thêm bản ghi.', 'Nhân ma trận không phải thao tác gộp dữ liệu.', 'split dùng để tách mảng.']),
  caseQuestion('Case: Bạn có 80 bản ghi đã xáo trộn và cần chia đều thành 4 batch để chạy thử. Lệnh nào phù hợp?', ['np.split(records, 4)', 'records.reshape(4)', 'np.vstack(records, 4)', 'np.unique(records, 4)'], 0, '`np.split(records, 4)` chia thành bốn phần bằng nhau khi 80 chia hết cho 4.', ['Đúng: kết quả là 4 mảng batch.', 'Shape 4 không chứa được 80 phần tử.', 'vstack không nhận đối số số batch như vậy.', 'unique không có nhiệm vụ chia batch.']),
  caseQuestion('Case: Báo cáo thử nghiệm cần chọn ngẫu nhiên 10 khách hàng khác nhau và tái lập đúng kết quả lần sau. Chọn lệnh.', ['np.random.default_rng(42).choice(customers, size=10, replace=False)', 'np.random.choice(customers, size=10, replace=True)', 'customers[:10]', 'np.repeat(customers, 10)'], 0, 'Seed 42 giúp tái lập và `replace=False` ngăn khách hàng bị chọn lặp.', ['Đúng: vừa tái lập vừa không lặp mẫu.', 'Có thể chọn trùng khách hàng và không cố định seed.', 'Chỉ chọn 10 bản ghi đầu, không ngẫu nhiên.', 'repeat tạo dữ liệu lặp, không lấy mẫu.']),
  caseQuestion('Case: Mô phỏng nhiễu cảm biến quanh 0 với độ lệch chuẩn 1 cho 100 điểm. API đúng?', ['rng.normal(0, 1, size=100)', 'rng.integers(0, 1, size=100)', 'rng.choice([0, 1], size=100)', 'np.zeros(100)'], 0, '`normal(0, 1)` tạo nhiễu theo phân phối chuẩn có mean 0 và std 1.', ['Đúng: tham số khớp mean, standard deviation và số mẫu.', 'integers chỉ cho số nguyên trong khoảng, không phải nhiễu chuẩn.', 'choice chỉ lấy các giá trị rời rạc 0/1.', 'zeros không có nhiễu.']),
  caseQuestion('Case: Công thức phối trộn nguyên liệu tạo hệ `A @ x = b`. Cách giải trực tiếp, ổn định là?', ['np.linalg.solve(A, b)', 'A / b', 'np.linalg.inv(A) + b', 'np.mean(A, b)'], 0, '`np.linalg.solve` giải trực tiếp hệ tuyến tính để tìm x.', ['Đúng: API dành cho hệ `A x = b`.', 'Chia phần tử không giải hệ ma trận.', 'Cộng nghịch đảo với b không phải phép giải hệ.', 'mean không liên quan đến nghiệm hệ.']),
  caseQuestion('Case: Hệ thống tìm kiếm cần so sánh cosine similarity, nên chuẩn hóa embedding `v` về norm 1. Chọn biểu thức.', ['v / np.linalg.norm(v)', 'v / np.mean(v)', 'np.sum(v)', 'v.reshape(1, -1)'], 0, 'Chia cho Euclidean norm đưa độ dài vector về 1.', ['Đúng: đây là L2 normalization.', 'Mean không phải độ dài vector.', 'sum chỉ tạo scalar.', 'reshape chỉ đổi shape, không đổi norm.']),
  caseQuestion('Case: Ma trận điểm `scores` có học sinh theo hàng, môn theo cột. Cần trung bình điểm từng môn để báo cáo. Chọn lệnh.', ['np.mean(scores, axis=0)', 'np.mean(scores, axis=1)', 'np.mean(scores)', 'np.max(scores, axis=0)'], 0, 'Giảm theo hàng bằng `axis=0` để còn một mean cho mỗi cột/môn.', ['Đúng: kết quả có một giá trị cho mỗi môn.', 'axis=1 tính trung bình từng học sinh.', 'Không còn phân tách theo môn.', 'max không phải trung bình.']),
  caseQuestion('Case: Hai ma trận chuyển đổi `A` và `B` cần được ghép theo phép nhân hàng–cột để áp dụng tuần tự. Toán tử đúng?', ['A @ B', 'A * B', 'A + B', 'np.vstack([A, B])'], 0, '`@` thực hiện matrix multiplication theo quy tắc hàng–cột.', ['Đúng: đây là phép hợp thành biến đổi tuyến tính.', '*` nhân từng ô, không phải hàng–cột.', 'Cộng ma trận không hợp thành hai biến đổi.', 'vstack chỉ ghép dữ liệu.']),
]);

addSourceQuestions('pandas', [
  caseQuestion('Case: File `orders.csv` vừa nhận từ đối tác. Bước nạp bảng dữ liệu phù hợp nhất?', ['pd.read_csv("orders.csv")', 'pd.DataFrame("orders.csv")', 'np.load("orders.csv")', 'pd.open_csv("orders.csv")'], 0, '`pd.read_csv` đọc CSV thành DataFrame để tiếp tục phân tích.', ['Đúng: đây là API đọc CSV của pandas.', 'Chuỗi tên file không tự trở thành bảng dữ liệu.', 'np.load không phải lựa chọn chuẩn cho CSV bảng.', 'pandas không có `open_csv`.']),
  caseQuestion('Case: Trước khi làm sạch đơn hàng, bạn cần biết kiểu dữ liệu, số non-null và bộ nhớ. Dùng gì?', ['df.info()', 'df.head()', 'df.shape', 'df.columns'], 0, '`info()` tóm tắt cột, dtype, non-null count và memory usage.', ['Đúng: cung cấp thông tin chất lượng cấu trúc cần kiểm tra.', 'head chỉ xem vài dòng mẫu.', 'shape chỉ có số hàng/cột.', 'columns chỉ liệt kê tên cột.']),
  caseQuestion('Case: Cần lấy name và score của dòng có nhãn index `SV-102`. Chọn cú pháp.', ['df.loc["SV-102", ["name", "score"]]', 'df.iloc["SV-102", ["name", "score"]]', 'df["SV-102"]', 'df.row("SV-102")'], 0, '`loc` chọn theo nhãn index và tên cột.', ['Đúng: nhãn string cần `loc`.', 'iloc chỉ nhận vị trí số nguyên.', 'Cú pháp này cố lấy một cột tên SV-102.', 'DataFrame không có row API này.']),
  caseQuestion('Case: Marketing chỉ muốn khách có `age >= 20` và `score >= 8`. Cách lọc đúng?', ['df[(df["age"] >= 20) & (df["score"] >= 8)]', 'df[df["age"] >= 20 and df["score"] >= 8]', 'df.filter(age >= 20)', 'df[(df["age"] >= 20) | (df["score"] >= 8)]'], 0, 'Hai điều kiện Series được kết hợp bằng `&` và ngoặc.', ['Đúng: chỉ giữ dòng thỏa đồng thời cả hai tiêu chí.', '`and` không hoạt động theo từng phần tử Series.', 'filter không nhận biểu thức điều kiện này.', '`|` sẽ lấy cả những khách chỉ đạt một điều kiện.']),
  caseQuestion('Case: Cột age có vài ô trống; nghiệp vụ cho phép thay bằng tuổi trung vị để hạn chế ảnh hưởng outlier. Chọn lệnh.', ['df["age"] = df["age"].fillna(df["age"].median())', 'df = df.dropna()', 'df["age"] = 0', 'df["age"].drop_duplicates()'], 0, 'Median phù hợp và phép gán cập nhật lại cột age.', ['Đúng: chỉ thay giá trị thiếu của age bằng median.', 'dropna xóa cả bản ghi có thiếu ở bất kỳ cột nào.', '0 thường không phản ánh tuổi thực tế.', 'Xóa trùng không xử lý giá trị thiếu.']),
  caseQuestion('Case: Mỗi email khách hàng chỉ giữ bản cập nhật gần nhất. Chọn cách dọn dữ liệu trùng.', ['df.drop_duplicates(subset=["email"], keep="last")', 'df.drop_duplicates(keep="first")', 'df.dropna(subset=["email"])', 'df["email"].unique()'], 0, '`subset` xác định khóa email và `keep="last"` giữ bản ghi cập nhật sau cùng.', ['Đúng: đúng khóa và đúng chính sách giữ bản ghi.', 'Thiếu subset email và giữ bản đầu, trái yêu cầu.', 'dropna chỉ bỏ email thiếu.', 'unique trả mảng email, không giữ toàn bộ dòng dữ liệu.']),
  caseQuestion('Case: Cột `order_date` chứa chuỗi ngày lẫn vài giá trị lỗi. Bạn cần parse để tính tháng, lỗi thành NaT. Chọn lệnh.', ['df["order_date"] = pd.to_datetime(df["order_date"], errors="coerce")', 'df["order_date"] = df["order_date"].astype(int)', 'df["order_date"] = pd.to_numeric(df["order_date"])', 'df["order_date"].split("-")'], 0, '`to_datetime(..., errors="coerce")` chuyển giá trị lỗi thành NaT an toàn.', ['Đúng: tạo cột datetime có thể dùng `.dt` sau đó.', 'Ép int không parse ngày đúng và lỗi với chuỗi ngày.', 'to_numeric không hiểu định dạng ngày.', 'split không tạo kiểu datetime.']),
  caseQuestion('Case: Báo cáo cần doanh thu trung bình theo chi nhánh. Đoạn code nào đúng?', ['df.groupby("branch")["revenue"].mean()', 'df["branch"].mean()', 'df.mean("branch", "revenue")', 'df.sort_values("branch")'], 0, 'Group theo branch rồi mean Series revenue tạo một giá trị cho mỗi chi nhánh.', ['Đúng: đây là tổng hợp theo nhóm.', 'Branch là nhãn, không có mean doanh thu.', 'Đây không phải API pandas hợp lệ.', 'Sắp xếp không tổng hợp số liệu.']),
  caseQuestion('Case: Bảng orders cần thêm tên khách từ customers theo customer_id, nhưng không được mất đơn hàng chưa có hồ sơ khách. Chọn join.', ['orders.merge(customers, on="customer_id", how="left")', 'orders.merge(customers, on="customer_id", how="inner")', 'pd.concat([orders, customers])', 'orders.dropna()'], 0, 'Left join giữ mọi dòng orders và gắn thông tin khách khi tìm thấy khóa.', ['Đúng: đáp ứng yêu cầu không làm mất đơn hàng.', 'Inner join làm rơi đơn hàng không có customer tương ứng.', 'concat không join theo customer_id.', 'dropna có thể xóa các đơn hàng cần giữ.']),
  caseQuestion('Case: Sau merge orders-customers, đội muốn bắt lỗi nếu một customer_id bên customers bị lặp khiến đơn hàng bị nhân bản. Chọn tham số.', ['validate="many_to_one"', 'ignore_index=True', 'ascending=False', 'errors="coerce"'], 0, '`validate="many_to_one"` yêu cầu nhiều orders chỉ ghép với tối đa một customer.', ['Đúng: ràng buộc cardinality và phát hiện khóa customer trùng.', 'ignore_index chỉ liên quan concat/index.', 'ascending liên quan sắp xếp.', 'errors coerce dùng trong parse/chuyển kiểu.']),
  caseQuestion('Case: Bạn có bảng doanh thu Jan, Feb, Mar cùng cột và muốn gộp thêm dòng, tạo index mới liên tục. Chọn lệnh.', ['pd.concat([jan, feb, mar], ignore_index=True)', 'jan.merge(feb).merge(mar)', 'jan + feb + mar', 'pd.pivot_table([jan, feb, mar])'], 0, '`concat` ghép bảng cùng schema theo hàng; `ignore_index` tạo index mới.', ['Đúng: đúng thao tác append các tháng.', 'merge yêu cầu khóa join và không phù hợp gộp cùng loại bản ghi.', 'Cộng DataFrame sẽ cộng ô theo index/cột.', 'pivot_table không nhận danh sách bảng theo cách này.']),
  caseQuestion('Case: Cần biến mã gender M/F thành nhãn Nam/Nữ mà không viết loop. Chọn biểu thức.', ['df["gender"].map({"M": "Nam", "F": "Nữ"})', 'df["gender"].merge({"M": "Nam"})', 'df.map("gender")', 'df["gender"].astype("Nam")'], 0, '`Series.map` áp dictionary cho từng mã trong cột.', ['Đúng: mapping rõ ràng trên một Series.', 'merge dùng DataFrame/Series khác, không phải dictionary mapping này.', 'map phải gọi trên Series mục tiêu.', 'astype chỉ đổi dtype, không chuyển từng giá trị.']),
  caseQuestion('Case: Tên khách có khoảng trắng thừa và viết hoa lộn xộn. Bạn cần "  ngUYỄn vĂn a " thành "Nguyễn Văn A". Chọn lệnh.', ['df["name"].str.strip().str.title()', 'df["name"].trim().upper()', 'pd.title(df["name"])', 'df["name"].replace(" ", "")'], 0, 'String accessor `.str` kết hợp `strip` và `title` làm sạch/chuẩn hóa tên.', ['Đúng: loại khoảng trắng biên và viết hoa đầu từ.', 'pandas không có `.trim()` và upper sẽ viết hoa toàn bộ.', 'pandas không có hàm title toàn cục này.', 'Xóa mọi khoảng trắng làm dính các từ trong tên.']),
  caseQuestion('Case: Muốn tách `email` thành hai cột username/domain cho báo cáo. Lệnh nào tạo được hai cột?', ['df["email"].str.split("@", n=1, expand=True)', 'df["email"].split("@")', 'pd.split(df["email"], "@")', 'df["email"].str.contains("@")'], 0, '`expand=True` trả DataFrame hai cột từ kết quả split.', ['Đúng: dùng string accessor và mở rộng thành cột.', 'Series không có `.split` trực tiếp ngoài `.str`.', 'pandas không có API split này.', 'contains chỉ tạo Boolean có/không có @.']),
  caseQuestion('Case: Cần tính thời gian giao của từng đơn sau khi đã parse hai cột ngày. Biểu thức đúng?', ['(df["delivered_at"] - df["order_date"]).dt.days', 'df["delivered_at"] / df["order_date"]', 'df["order_date"].dt.day', 'df["delivered_at"].mean()'], 0, 'Trừ hai datetime tạo timedelta; `.dt.days` lấy số ngày giao.', ['Đúng: tạo một giá trị số ngày cho từng đơn.', 'Không thể chia hai timestamp để lấy thời lượng.', 'day chỉ là ngày trong tháng của thời điểm đặt.', 'mean không tạo thời lượng cho từng đơn.']),
  caseQuestion('Case: Ban quản lý cần tổng sales theo department (hàng) và month (cột), ô thiếu hiển thị 0. API phù hợp?', ['pd.pivot_table(df, values="sales", index="department", columns="month", aggfunc="sum", fill_value=0)', 'pd.melt(df, id_vars=["department"] )', 'df.groupby("month").head()', 'df.sort_values("department")'], 0, 'Pivot table tạo báo cáo chéo và `fill_value=0` lấp ô thiếu.', ['Đúng: khớp cấu trúc báo cáo tổng hợp mong muốn.', 'melt chuyển wide sang long, ngược nhu cầu.', 'groupby head không tạo ma trận tổng hợp.', 'Sắp xếp không tổng hợp sales.']),
  caseQuestion('Case: Bảng điểm có cột Toan, Ly, Hoa; cần chuyển thành từng dòng `student, subject, score` để vẽ biểu đồ. Chọn API.', ['pd.melt(scores, id_vars=["student"], var_name="subject", value_name="score")', 'pd.pivot_table(scores)', 'scores.reshape(-1, 1)', 'scores.drop(columns=["student"])'], 0, '`melt` chuyển các cột môn thành cặp subject/score dạng long.', ['Đúng: tạo cấu trúc long cho mỗi môn của mỗi học sinh.', 'pivot_table thường tổng hợp, không unpivot bảng này.', 'DataFrame không reshape như ndarray cho mục tiêu này.', 'Xóa student làm mất khóa định danh.']),
]);
